name: "Persona Submission"
description: "Share your AI persona with the HomePilot community"
title: "[Persona] "
labels: ["persona-submission"]
body:
  - type: markdown
    attributes:
      value: |
        **How it works:** Fill in the details, attach your persona, and submit.
        A maintainer will review it and publish it to the gallery.

        > **Export:** In HomePilot go to **My Projects** > find your persona > click **Export**.
        > Then put the `.hpersona` file inside a `.zip` before uploading below.

  - type: input
    id: persona_name
    attributes:
      label: Persona Name
      description: "Display name (e.g. 'Scarlett', 'Atlas')."
      placeholder: "Scarlett"
    validations:
      required: true

  - type: textarea
    id: short_description
    attributes:
      label: Short Description
      description: "One-line summary for the gallery card (max 120 characters)."
      placeholder: "Executive secretary — professional, proactive, and always two steps ahead."
    validations:
      required: true

  - type: dropdown
    id: content_rating
    attributes:
      label: Content Rating
      description: "Is this persona safe for all audiences?"
      options:
        - "SFW (Safe for Work)"
        - "NSFW (Adult Content)"
    validations:
      required: true

  - type: dropdown
    id: tags
    attributes:
      label: Tags
      description: "Select all that apply."
      multiple: true
      options:
        - professional
        - creative
        - entertainment
        - productivity
        - coding
        - research
        - roleplay
        - lifestyle
    validations:
      required: true

  - type: textarea
    id: package_file
    attributes:
      label: Persona Package (.zip)
      description: |
        **Put your `.hpersona` file inside a `.zip` and drag it here.**
        GitHub does not allow `.hpersona` uploads directly, so wrap it in a zip first.
        (Right-click the file > Compress / Send to > Compressed folder)
      placeholder: "Drag your .zip file here..."
    validations:
      required: true

  - type: checkboxes
    id: agreements
    attributes:
      label: Agreement
      options:
        - label: "I have the right to share this persona and agree to publish it under the Apache 2.0 license. The content rating above is accurate."
          required: true
