apiVersion: v1
kind: Service
metadata:
  name: avatar-service
  namespace: homepilot
  labels:
    app.kubernetes.io/name: avatar-service
    app.kubernetes.io/part-of: homepilot
spec:
  selector:
    app: avatar-service
  ports:
    - name: http
      port: 8020
      targetPort: 8020
      protocol: TCP
  type: ClusterIP
