apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepilot

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc-models.yaml
  - avatar-service-deployment.yaml
  - avatar-service-service.yaml

commonLabels:
  app.kubernetes.io/part-of: homepilot
