#!/usr/bin/env bash
# ==============================================================================
#  restore-mcp-server.sh  –  Clean-reset MCP Context Forge and restore login
#
#  Drops the old database, re-bootstraps the admin user with relaxed password
#  rules, and restarts the gateway so you can log in immediately.
#
#  Usage:
#    bash scripts/restore-mcp-server.sh
#
#  Login after restore:
#    URL:      http://localhost:4444/admin/login
#    Email:    admin@example.com
#    Password: changeme
# ==============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Try sibling directory first, then nested
if [ -d "$ROOT/../mcp-context-forge" ]; then
    _DEFAULT_MCP_DIR="$(cd "$ROOT/../mcp-context-forge" && pwd)"
elif [ -d "$ROOT/mcp-context-forge" ]; then
    _DEFAULT_MCP_DIR="$ROOT/mcp-context-forge"
else
    _DEFAULT_MCP_DIR="$ROOT/mcp-context-forge"
fi
MCP_DIR="${MCP_CONTEXT_FORGE_DIR:-$_DEFAULT_MCP_DIR}"
MCP_GATEWAY_PORT="${MCP_GATEWAY_PORT:-4444}"
MCP_GATEWAY_HOST="${MCP_GATEWAY_HOST:-127.0.0.1}"

# ── Preflight checks ────────────────────────────────────────────────────────
if [ ! -d "$MCP_DIR" ]; then
    echo "  ERROR: mcp-context-forge not found at $MCP_DIR"
    echo "  Set MCP_CONTEXT_FORGE_DIR if it lives elsewhere."
    exit 1
fi

# Detect python
if [ -x "$MCP_DIR/.venv/bin/python" ]; then
    PYTHON="$MCP_DIR/.venv/bin/python"
elif [ -x "$HOME/.venv/mcpgateway/bin/python" ]; then
    PYTHON="$HOME/.venv/mcpgateway/bin/python"
else
    echo "  ERROR: No venv found. Run 'make venv install-dev' in mcp-context-forge first."
    exit 1
fi

echo ""
echo "  ============================================"
echo "   MCP Context Forge – Restore"
echo "  ============================================"
echo ""

# ── 1. Stop any running gateway ─────────────────────────────────────────────
echo "  [1/5] Stopping running gateway processes..."
pkill -f "mcpgateway.main:app" 2>/dev/null || true
pkill -f "uvicorn mcpgateway" 2>/dev/null || true
sleep 1
echo "        Done."

# ── 2. Remove old database ──────────────────────────────────────────────────
echo "  [2/5] Removing old database..."
DB_FILE="$MCP_DIR/mcp.db"
if [ -f "$DB_FILE" ]; then
    rm -f "$DB_FILE"
    echo "        Removed $DB_FILE"
else
    echo "        No existing DB found (clean state)."
fi
# Also remove WAL/SHM files if present
rm -f "$DB_FILE-wal" "$DB_FILE-shm" 2>/dev/null || true

# ── 3. Ensure .env exists with working defaults ─────────────────────────────
echo "  [3/5] Ensuring .env has working auth defaults..."
ENV_FILE="$MCP_DIR/.env"

# Write or patch the critical auth settings
ensure_env_var() {
    local key="$1" value="$2"
    if [ -f "$ENV_FILE" ] && grep -q "^${key}=" "$ENV_FILE"; then
        sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
    else
        echo "${key}=${value}" >> "$ENV_FILE"
    fi
}

# Create minimal .env if missing
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << 'ENVEOF'
# Auto-generated by restore-mcp-server.sh
BASIC_AUTH_USER=admin
BASIC_AUTH_PASSWORD=changeme
JWT_SECRET_KEY=my-test-key
AUTH_ENCRYPTION_SECRET=my-test-salt
HOST=0.0.0.0
PORT=4444
APP_DOMAIN=http://localhost
SECURE_COOKIES=false
MCPGATEWAY_UI_ENABLED=true
MCPGATEWAY_ADMIN_API_ENABLED=true
LOG_LEVEL=INFO
ENVEOF
fi

# Ensure password complexity is relaxed for local dev
ensure_env_var "PLATFORM_ADMIN_EMAIL"                       "admin@example.com"
ensure_env_var "PLATFORM_ADMIN_PASSWORD"                    "changeme"
ensure_env_var "DEFAULT_USER_PASSWORD"                      "changeme"
ensure_env_var "PASSWORD_REQUIRE_UPPERCASE"                 "false"
ensure_env_var "PASSWORD_REQUIRE_LOWERCASE"                 "false"
ensure_env_var "PASSWORD_REQUIRE_SPECIAL"                   "false"
ensure_env_var "PASSWORD_REQUIRE_NUMBERS"                   "false"
ensure_env_var "PASSWORD_MIN_LENGTH"                        "6"
ensure_env_var "PASSWORD_CHANGE_ENFORCEMENT_ENABLED"        "false"
ensure_env_var "ADMIN_REQUIRE_PASSWORD_CHANGE_ON_BOOTSTRAP" "false"
ensure_env_var "SECURE_COOKIES"                             "false"

echo "        .env ready."

# ── 4. Bootstrap fresh database ──────────────────────────────────────────────
echo "  [4/5] Bootstrapping fresh database..."
cd "$MCP_DIR"
$PYTHON -m mcpgateway.bootstrap_db 2>&1 | grep -E "(INFO|ERROR|WARNING).*(__main__|admin|role|Database)" || true
cd "$ROOT"
echo "        Database bootstrapped."

# ── 5. Start the gateway ────────────────────────────────────────────────────
echo "  [5/5] Starting MCP Gateway on port $MCP_GATEWAY_PORT..."
cd "$MCP_DIR"
$PYTHON -m uvicorn mcpgateway.main:app \
    --host "$MCP_GATEWAY_HOST" \
    --port "$MCP_GATEWAY_PORT" \
    --log-level warning &
GW_PID=$!
cd "$ROOT"

# Wait for it to be ready
for i in $(seq 1 30); do
    if curl -sf "http://${MCP_GATEWAY_HOST}:${MCP_GATEWAY_PORT}/health" >/dev/null 2>&1; then
        break
    fi
    if [ "$i" = "30" ]; then
        echo "  WARNING: Gateway may still be starting..."
    fi
    sleep 1
done

# ── Verify login ────────────────────────────────────────────────────────────
LOGIN_RESP=$(curl -sf -X POST "http://${MCP_GATEWAY_HOST}:${MCP_GATEWAY_PORT}/auth/login" \
    -H "Content-Type: application/json" \
    -d '{"email":"admin@example.com","password":"changeme"}' 2>/dev/null || echo "FAIL")

if echo "$LOGIN_RESP" | grep -q "access_token"; then
    echo ""
    echo "  ============================================"
    echo "   RESTORE COMPLETE"
    echo "  ============================================"
    echo ""
    echo "   Gateway PID:  $GW_PID"
    echo "   Admin UI:     http://localhost:${MCP_GATEWAY_PORT}/admin/login"
    echo "   Email:        admin@example.com"
    echo "   Password:     changeme"
    echo ""
    echo "   Login verified OK"
    echo "  ============================================"
else
    echo ""
    echo "  WARNING: Gateway started but login test failed."
    echo "  Check logs: tail -f $MCP_DIR/logs/mcpgateway.log"
    echo "  Gateway PID: $GW_PID"
fi
