#!/usr/bin/env python3
"""Audit duplicate TS/JS source pairs under frontend/src.

The HomePilot frontend is TypeScript-first (``tsc -b && vite build``), but the
source tree also carries stale ``.jsx``/``.js`` mirrors committed long ago and
never regenerated by ``tsc -b`` until a full build runs. Those mirrors are
dead artifacts (Vite builds from ``.tsx`` directly) — this tool identifies
them and helps plan their removal.

Subcommands
-----------
inventory   List every basename that exists as both TS/TSX and JS/JSX.
imports     Show who imports what. With a path argument, list importers of
            that single file. With no argument, list importer counts for
            each variant of every duplicate pair.
orphans     List source files nothing imports (reachability from main.tsx).
plan        Full cleanup report: inventory + per-group winner recommendation,
            grouped by top-level folder for staged PRs.
ci          Exit 1 if any TS/JS duplicate exists. Intended as a CI guard.

Examples
--------
    python tools/frontend_audit.py inventory
    python tools/frontend_audit.py --json inventory
    python tools/frontend_audit.py imports frontend/src/ui/App.tsx
    python tools/frontend_audit.py plan > cleanup-plan.md
    python tools/frontend_audit.py ci && echo clean

Zero external dependencies. Python 3.10+.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

SOURCE_EXTS: tuple[str, ...] = (".ts", ".tsx", ".js", ".jsx")
TS_EXTS: frozenset[str] = frozenset({".ts", ".tsx"})
JS_EXTS: frozenset[str] = frozenset({".js", ".jsx"})
SKIP_DIRS: frozenset[str] = frozenset(
    {"node_modules", "dist", "build", "__pycache__", ".vite", "coverage", ".turbo"}
)

# Matches static imports, side-effect imports, require(), and dynamic import().
IMPORT_RE = re.compile(
    r"""(?x)
    (?:
        \bimport\s+(?:type\s+)?[\s\S]*?\bfrom\s*['"]([^'"]+)['"]
      | \bimport\s*['"]([^'"]+)['"]
      | \brequire\s*\(\s*['"]([^'"]+)['"]\s*\)
      | \bimport\s*\(\s*['"]([^'"]+)['"]\s*\)
    )
    """
)


@dataclass
class SourceFile:
    path: Path          # absolute
    rel: Path           # relative to frontend/src
    ext: str
    size: int
    mtime: float


@dataclass
class DuplicateGroup:
    rel_stem: Path                  # e.g. ui/App  (no extension, relative to frontend/src)
    ts_variants: list[SourceFile] = field(default_factory=list)
    js_variants: list[SourceFile] = field(default_factory=list)

    @property
    def all_variants(self) -> list[SourceFile]:
        return [*self.ts_variants, *self.js_variants]


def find_frontend_src(start: Path) -> Path:
    """Walk up from *start* until a directory containing ``frontend/src`` is found."""
    cur = start.resolve()
    for d in (cur, *cur.parents):
        cand = d / "frontend" / "src"
        if cand.is_dir():
            return cand
    sys.exit(f"ERROR: frontend/src not found searching upward from {start}")


def iter_sources(src: Path) -> Iterable[SourceFile]:
    """Yield every non-skipped source file under *src*."""
    for p in src.rglob("*"):
        if not p.is_file() or p.suffix not in SOURCE_EXTS:
            continue
        if any(part in SKIP_DIRS for part in p.relative_to(src).parts):
            continue
        st = p.stat()
        yield SourceFile(
            path=p,
            rel=p.relative_to(src),
            ext=p.suffix,
            size=st.st_size,
            mtime=st.st_mtime,
        )


def group_duplicates(files: list[SourceFile]) -> list[DuplicateGroup]:
    """Group files by (dirname, stem); return only groups with both TS and JS variants."""
    by_stem: dict[Path, list[SourceFile]] = defaultdict(list)
    for f in files:
        by_stem[f.rel.with_suffix("")].append(f)
    groups: list[DuplicateGroup] = []
    for stem, group in by_stem.items():
        ts = [f for f in group if f.ext in TS_EXTS]
        js = [f for f in group if f.ext in JS_EXTS]
        if ts and js:
            groups.append(DuplicateGroup(rel_stem=stem, ts_variants=ts, js_variants=js))
    groups.sort(key=lambda g: str(g.rel_stem))
    return groups


def resolve_import(from_file: Path, spec: str) -> Path | None:
    """Resolve a *relative* import spec to an actual file on disk. Package
    specifiers (not starting with '.') return None."""
    if not spec or not spec.startswith("."):
        return None
    base = (from_file.parent / spec).resolve()
    # Spec already has an extension and the file exists.
    if base.suffix in SOURCE_EXTS and base.is_file():
        return base
    # Bare spec → try each known extension.
    for ext in SOURCE_EXTS:
        cand = base.parent / (base.name + ext)
        if cand.is_file():
            return cand
    # Directory spec → look for index.
    if base.is_dir():
        for ext in SOURCE_EXTS:
            cand = base / f"index{ext}"
            if cand.is_file():
                return cand
    return None


def build_import_graph(files: list[SourceFile]) -> dict[Path, set[Path]]:
    """Return {imported_file → {importer_files}}. Paths are absolute."""
    edges: dict[Path, set[Path]] = defaultdict(set)
    for f in files:
        try:
            text = f.path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for match in IMPORT_RE.finditer(text):
            spec = next((g for g in match.groups() if g), None)
            if not spec:
                continue
            target = resolve_import(f.path, spec)
            if target is not None:
                edges[target].add(f.path)
    return edges


def entry_points(src: Path) -> set[Path]:
    """Known top-level entry points Vite traces from."""
    names = ("main.tsx", "main.ts", "main.jsx", "main.js", "index.tsx", "index.ts")
    return {src / n for n in names if (src / n).is_file()}


def reachable(graph: dict[Path, set[Path]], roots: set[Path]) -> set[Path]:
    """Reverse-traverse: everything that *roots* (transitively) imports."""
    # The graph is reverse (target → importers). We need forward traversal
    # from roots through imports. Rebuild a forward adjacency on demand.
    forward: dict[Path, set[Path]] = defaultdict(set)
    for target, importers in graph.items():
        for imp in importers:
            forward[imp].add(target)
    seen: set[Path] = set()
    stack = list(roots)
    while stack:
        node = stack.pop()
        if node in seen:
            continue
        seen.add(node)
        stack.extend(forward.get(node, ()))
    return seen


def pick_canonical(group: DuplicateGroup, graph: dict[Path, set[Path]]) -> SourceFile:
    """Recommend which variant to keep: TS/TSX wins unless the JS side has
    *strictly* more importers (which would indicate the JS copy is the live
    one and the TS copy is orphaned/stale)."""
    ts_importers = sum(len(graph.get(f.path, set())) for f in group.ts_variants)
    js_importers = sum(len(graph.get(f.path, set())) for f in group.js_variants)
    if js_importers > ts_importers:
        # JS side is actually wired in — surface that for review.
        return group.js_variants[0]
    # Default policy: TS/TSX is canonical.
    return group.ts_variants[0]


# ── Output helpers ────────────────────────────────────────────────────────

def _fmt_size(n: int) -> str:
    for unit in ("B", "KiB", "MiB"):
        if n < 1024:
            return f"{n:,.0f}{unit}"
        n //= 1024
    return f"{n}GiB"


def _tag(ext: str) -> str:
    return "TS" if ext in TS_EXTS else "JS"


# ── Subcommands ────────────────────────────────────────────────────────────

def cmd_inventory(src: Path, *, as_json: bool) -> int:
    files = list(iter_sources(src))
    dups = group_duplicates(files)
    if as_json:
        payload = {
            "frontend_src": str(src),
            "total_files": len(files),
            "ts_count": sum(1 for f in files if f.ext in TS_EXTS),
            "js_count": sum(1 for f in files if f.ext in JS_EXTS),
            "duplicate_groups": len(dups),
            "groups": [
                {
                    "stem": str(g.rel_stem),
                    "variants": [
                        {"rel": str(f.rel), "ext": f.ext, "size": f.size, "mtime": f.mtime}
                        for f in g.all_variants
                    ],
                }
                for g in dups
            ],
        }
        print(json.dumps(payload, indent=2))
        return 0
    total = len(files)
    ts = sum(1 for f in files if f.ext in TS_EXTS)
    js = sum(1 for f in files if f.ext in JS_EXTS)
    print(f"Scanned {total} files under {src}")
    print(f"  TS/TSX: {ts}")
    print(f"  JS/JSX: {js}")
    print(f"  Duplicate TS/JS pairs: {len(dups)}")
    print()
    if not dups:
        print("No duplicates. ✓")
        return 0
    for g in dups:
        print(f"• {g.rel_stem}")
        for f in g.all_variants:
            print(f"    [{_tag(f.ext)}] {f.rel.name:<40} {_fmt_size(f.size):>10}")
    return 0


def cmd_imports(src: Path, target_arg: str | None, *, as_json: bool) -> int:
    files = list(iter_sources(src))
    graph = build_import_graph(files)

    if target_arg:
        t = Path(target_arg).resolve()
        importers = sorted(graph.get(t, set()))
        if as_json:
            print(json.dumps(
                {"target": str(t), "importers": [str(p) for p in importers]},
                indent=2,
            ))
            return 0
        print(f"Importers of {t}:")
        if not importers:
            print("  (none — this file is not referenced by any source)")
            return 0
        for p in importers:
            print(f"  {p.relative_to(src)}")
        return 0

    # No target: report per-variant importer counts for each duplicate group.
    dups = group_duplicates(files)
    if as_json:
        payload = [
            {
                "stem": str(g.rel_stem),
                "variants": [
                    {
                        "rel": str(f.rel),
                        "ext": f.ext,
                        "importer_count": len(graph.get(f.path, set())),
                        "importers": sorted(str(p.relative_to(src)) for p in graph.get(f.path, set())),
                    }
                    for f in g.all_variants
                ],
            }
            for g in dups
        ]
        print(json.dumps(payload, indent=2))
        return 0
    for g in dups:
        print(f"• {g.rel_stem}")
        for f in g.all_variants:
            imps = graph.get(f.path, set())
            print(f"    [{_tag(f.ext)}] {f.rel.name:<40} imported by {len(imps):>3d} file(s)")
    return 0


def cmd_orphans(src: Path, *, as_json: bool) -> int:
    files = list(iter_sources(src))
    graph = build_import_graph(files)
    roots = entry_points(src)
    reached = reachable(graph, roots)
    # Exclude common "entry-point-ish" files that Vite / tests pull in outside the graph:
    # test files, test setups, type-declaration files, and the entry points themselves.
    def is_entrypoint_ish(p: Path) -> bool:
        name = p.name
        if name in {"main.tsx", "main.ts", "main.jsx", "main.js", "index.tsx", "index.ts"}:
            return True
        if name.endswith(".test.ts") or name.endswith(".test.tsx") \
                or name.endswith(".test.js") or name.endswith(".test.jsx"):
            return True
        if name.endswith(".d.ts"):
            return True
        return False

    orphans = [f for f in files if f.path not in reached and not is_entrypoint_ish(f.path)]
    orphans.sort(key=lambda f: str(f.rel))
    if as_json:
        print(json.dumps({
            "entry_points": [str(p.relative_to(src)) for p in roots],
            "orphans": [
                {"rel": str(f.rel), "ext": f.ext, "size": f.size}
                for f in orphans
            ],
        }, indent=2))
        return 0
    print(f"Entry points traced: {', '.join(str(p.relative_to(src)) for p in roots) or '(none found)'}")
    print(f"Orphans (not reachable from any entry point, excluding tests/.d.ts): {len(orphans)}")
    print()
    for f in orphans:
        print(f"  [{_tag(f.ext)}] {f.rel}")
    return 0


def cmd_plan(src: Path) -> int:
    """Markdown-formatted cleanup plan. Easy to paste into a PR description."""
    files = list(iter_sources(src))
    graph = build_import_graph(files)
    dups = group_duplicates(files)

    # Bucket duplicate groups by first path component for staged cleanup PRs.
    by_folder: dict[str, list[DuplicateGroup]] = defaultdict(list)
    for g in dups:
        parts = g.rel_stem.parts
        by_folder[parts[0] if parts else "(root)"].append(g)

    total_bytes_js = sum(f.size for g in dups for f in g.js_variants)

    out: list[str] = []
    out.append("# Frontend TS/JS duplicate cleanup plan")
    out.append("")
    out.append(f"- Files scanned: **{len(files)}**")
    out.append(f"- Duplicate basename pairs: **{len(dups)}**")
    out.append(f"- Approximate JS bytes recoverable: **{_fmt_size(total_bytes_js)}**")
    out.append("")
    out.append("## Staged removal order (one PR per folder)")
    out.append("")
    for folder in sorted(by_folder):
        groups = by_folder[folder]
        out.append(f"### `{folder}/` — {len(groups)} pair(s)")
        out.append("")
        out.append("| Basename | Keep (canonical) | Delete | TS imports | JS imports |")
        out.append("|---|---|---|---:|---:|")
        for g in groups:
            winner = pick_canonical(g, graph)
            ts_imp = sum(len(graph.get(f.path, set())) for f in g.ts_variants)
            js_imp = sum(len(graph.get(f.path, set())) for f in g.js_variants)
            keep_rel = winner.rel
            delete_rels = [f.rel for f in g.all_variants if f.path != winner.path]
            flag = " ⚠️" if js_imp > ts_imp else ""
            out.append(
                f"| `{g.rel_stem}` | `{keep_rel}`{flag} | "
                f"{', '.join(f'`{r}`' for r in delete_rels)} | "
                f"{ts_imp} | {js_imp} |"
            )
        out.append("")
    out.append("## Legend")
    out.append("")
    out.append("- **Keep (canonical)** is the variant the cleanup PR should retain. TS/TSX by default.")
    out.append("- ⚠️ flags groups where the JS side has more importers than the TS side —")
    out.append("  the JS copy may actually be the live one. Review manually before deleting.")
    out.append("- **TS imports / JS imports** are the number of files that import each variant.")
    out.append("")
    out.append("## Suggested CI guard")
    out.append("")
    out.append("Run this in CI to prevent regressions once cleanup starts:")
    out.append("")
    out.append("```bash")
    out.append("python tools/frontend_audit.py ci")
    out.append("```")
    print("\n".join(out))
    return 0


def cmd_ci(src: Path, *, quiet: bool) -> int:
    files = list(iter_sources(src))
    dups = group_duplicates(files)
    if not dups:
        if not quiet:
            print("frontend_audit: no TS/JS duplicates. ✓")
        return 0
    if not quiet:
        print(f"frontend_audit: FAIL — {len(dups)} duplicate basename pair(s) under {src}:",
              file=sys.stderr)
        for g in dups:
            variants = ", ".join(f"{f.ext}" for f in g.all_variants)
            print(f"  {g.rel_stem} [{variants}]", file=sys.stderr)
    return 1


# ── Entry point ────────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="frontend_audit",
        description="Audit duplicate TS/JS source pairs under frontend/src.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Starting directory (default: cwd). Searches upward for frontend/src.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit JSON instead of human-readable output (ignored by 'plan').",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("inventory", help="list every TS/JS duplicate basename pair")
    imp = sub.add_parser("imports", help="show importers of a file, or per-variant counts for all duplicates")
    imp.add_argument("target", nargs="?", help="Optional file path to report importers for")
    sub.add_parser("orphans", help="list source files not reachable from main.tsx")
    sub.add_parser("plan", help="print a markdown cleanup plan")
    ci = sub.add_parser("ci", help="exit 1 if any TS/JS duplicate exists")
    ci.add_argument("--quiet", action="store_true")

    args = parser.parse_args(argv)
    src = find_frontend_src(args.root)

    if args.cmd == "inventory":
        return cmd_inventory(src, as_json=args.json)
    if args.cmd == "imports":
        return cmd_imports(src, args.target, as_json=args.json)
    if args.cmd == "orphans":
        return cmd_orphans(src, as_json=args.json)
    if args.cmd == "plan":
        return cmd_plan(src)
    if args.cmd == "ci":
        return cmd_ci(src, quiet=args.quiet)
    parser.error(f"unknown command: {args.cmd}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
